# Generated by Django 4.1.5 on 2023-01-14 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_user_updated_at_product"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product", old_name="product_name", new_name="Product_name",
        ),
    ]
