# Generated by Django 4.1.5 on 2023-01-14 16:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_rename_product_name_product_product_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="product", old_name="Product_name", new_name="product_name",
        ),
    ]
